# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import presentation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Le nom du projet', max_length=100, null=True)),
                ('owner_image', models.ImageField(help_text=b'Photo du chef du projet', null=True, upload_to=presentation.models.user_directory_path)),
                ('creation_date', models.PositiveIntegerField(help_text=b'date de cr\xc3\xa9ation', null=True)),
                ('contact_name', models.CharField(help_text=b'nom du contact de r\xc3\xa9f\xc3\xa9rence', max_length=100, null=True)),
                ('email', models.EmailField(help_text=b'email de contact', max_length=254, null=True)),
                ('telephone', models.CharField(help_text=b'num\xc3\xa9ro de t\xc3\xa9l\xc3\xa9phone', max_length=14, null=True)),
                ('web_site', models.URLField(help_text=b'site Web du projet', null=True)),
                ('structure', models.CharField(help_text=b'structure administrative du projet', max_length=100, null=True)),
                ('location_today', models.ImageField(help_text=b"pr\xc3\xa9sence du projet aujourd'hui", null=True, upload_to=presentation.models.user_directory_path)),
                ('location_target', models.ImageField(help_text=b"pr\xc3\xa9vision d'\xc3\xa9volution g\xc3\xa9ographique", null=True, upload_to=presentation.models.user_directory_path)),
                ('logo', models.ImageField(help_text=b'photo du logo du projet', null=True, upload_to=presentation.models.user_directory_path)),
                ('project_structure', models.ImageField(help_text=b'image de la strcuture globale du projet', null=True, upload_to=presentation.models.user_directory_path)),
                ('workers', models.TextField(help_text=b'participants au projet - b\xc3\xa9n\xc3\xa9vols, salari\xc3\xa9s', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, null=True)),
                ('content', models.TextField()),
                ('coordinate_x', models.IntegerField()),
                ('coordinate_y', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentation.Project')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='presentation.Project'),
        ),
    ]
