# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('code', models.CharField(max_length=5)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default=b'France', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='EventAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentation.Address')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentation.Event')),
            ],
        ),
    ]
